// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ftpclient} from '../models';

export function ChangeDirectory(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ListDirectory():Promise<Array<ftpclient.FtpEntry>>;
